author: Fumito Ito
author_url: https://github.com/fumito-ito
github_url: https://github.com/fumito-ito/RxDifferenceKit
module: RxDifferenceKit
readme: README.md
output: docs
theme: apple
clean: true
skip_undocumented: true
xcodebuild_arguments:
  - -sdk
  - iphonesimulator
